name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  keygen:
    runs-on: ubuntu-latest
    steps:
    - name: Generate
      run: |
        keytool -genkeypair -v \
          -keystore vidmax.keystore \
          -alias vidmax \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass vidmax123 \
          -keypass vidmax123 \
          -dname "CN=VidMax, OU=Dev, O=Rihad, L=Sylhet, S=Sylhet, C=BD"
        echo "KEYSTORE_BASE64:"
        base64 vidmax.keystore
